### ISSUE TITLE
Issue with Xcode 10.2 Swift version 4.1

### ISSUE THREAD

**Issue by jasvindersingh-evon** [iampossible/Cordova-DocPicker#7]
Hi,

I created a new project using Ionic command and then added the plugin using the commands specified at Ionic portal specified here - https://ionicframework.com/docs/native/document-picker

After adding the plugin and trying to create build in Xcode 10.2 swift version 4.1, there is an error in function `callPicker`.

The error is **Cannot convert value of type '[Character]' to expected argument type '[String]'** on line number 51.

Please fix the code for Swift version 4.1. It must support Swift version 3.0.

Also please note that Apple is not allowing the builds to be uploaded that are created from Xcode 9.0+. So its a need to use Xcode 10.1 with iOS 12.1 SDK. Xcode 10.1 has the support of swift version 3.0 so the build gets successfully created in that version but not in Xcode 10.2.

Please check attached screenshot below for reference.
![Screen Shot 2019-04-12 at 11 43 16 AM](https://user-images.githubusercontent.com/10975369/56016044-ae841200-5d18-11e9-8882-a5032f6d6110.png)

**Comment by AmadeuReal** [comment]
Instead of using ionic script, can you pull the plugin from the repo? 
Using: `cordova plugin add https://github.com/iampossible/Cordova-DocPicker.git`.

I don't actually know why installing thru Ionic, it fetches an old version. I keep looking into that, but your issue it's fixed.

I'm able to create, build and deploy to a real device a freshly created project using Xcode 10.2. 

If you're still having issues, feel free to report and will try to assist you!

**Comment by jasvindersingh-evon** [comment]
@AmadeuReal : Thats true, if I add plugin using `cordova plugin add https://github.com/iampossible/Cordova-DocPicker.git`, it works. 

Can't we connect with Ionic team and tell them to fix something at their end so that with ionic script it should fetch newer version. You can guide me and I will raise issue at their end.

**Comment by AmadeuReal** [comment]
Yeah, you are right. But it think that with this update it will work.
The thing is that on the `plugin.xml` file, the version value was `0.0.1` instead of the current value…  So this is might have been the problem. We probably just have to wait a bit, until ionic start fetching the right version. 🤞🏿

**Comment by jasvindersingh-evon** [comment]
Hi @AmadeuReal : Please check the link below. I contacted Ionic but they said that its not an Ionic issue. Its the issue from npm registry.

https://github.com/ionic-team/ionic/issues/18057#issuecomment-484227106

**Comment by AmadeuReal** [comment]
Thanks @jasvindersingh-evon! I'm equating all the possible actions to resolve this issue. Since there is already an entry on npm to this repo, I can't since update it… Already contacted npm support team, to see what they suggest me to do.

One possible solution is to create a new npm package… Let's see.
